# ~/.config/starship.toml

# wait for ruby --version
command_timeout = 900

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[git_status]
conflicted = "ğŸ’¥${count}"
ahead = "â¬†${count}"
behind = "â¬‡${count}"
diverged = "ğŸ”± â¬†${ahead_count} â¬‡${behind_count}"
untracked = "ğŸ¤·â€${count}"
stashed = "ğŸ“¦${count}"
modified = "ğŸ“${count}"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…${count}"
deleted = "ğŸš®${count}"

[package]
disabled = true
